from . import res_users_inherit
from . import team_inherit
from . import coach_inherit
from . import age_group_inherit
from . import account_move
from . import partner_inherit_domain
from . import sale_order
from . import product_template
from . import sale_subscription_plan
